package com.domain.sysassets;
// Generated 01/08/2018 09:51:25 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CategoriaActivo generated by hbm2java
 */
public class CategoriaActivo  implements java.io.Serializable {


     private String categoria;
     private String descripcion;
     private String ctaGasto;
     private String ctaDepreciacion;
     private Set<TipoActivo> tipoActivos = new HashSet<TipoActivo>(0);

    public CategoriaActivo() {
    }

	
    public CategoriaActivo(String categoria) {
        this.categoria = categoria;
    }
    public CategoriaActivo(String categoria, String descripcion, String ctaGasto, String ctaDepreciacion, Set<TipoActivo> tipoActivos) {
       this.categoria = categoria;
       this.descripcion = descripcion;
       this.ctaGasto = ctaGasto;
       this.ctaDepreciacion = ctaDepreciacion;
       this.tipoActivos = tipoActivos;
    }
   
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getCtaGasto() {
        return this.ctaGasto;
    }
    
    public void setCtaGasto(String ctaGasto) {
        this.ctaGasto = ctaGasto;
    }
    public String getCtaDepreciacion() {
        return this.ctaDepreciacion;
    }
    
    public void setCtaDepreciacion(String ctaDepreciacion) {
        this.ctaDepreciacion = ctaDepreciacion;
    }
    public Set<TipoActivo> getTipoActivos() {
        return this.tipoActivos;
    }
    
    public void setTipoActivos(Set<TipoActivo> tipoActivos) {
        this.tipoActivos = tipoActivos;
    }




}


