package com.domain.sysassets;
// Generated 01/08/2018 09:51:25 PM by Hibernate Tools 4.3.1



/**
 * DepartamentoId generated by hbm2java
 */
public class DepartamentoId  implements java.io.Serializable {


     private String codCia;
     private String codDepar;

    public DepartamentoId() {
    }

    public DepartamentoId(String codCia, String codDepar) {
       this.codCia = codCia;
       this.codDepar = codDepar;
    }
   
    public String getCodCia() {
        return this.codCia;
    }
    
    public void setCodCia(String codCia) {
        this.codCia = codCia;
    }
    public String getCodDepar() {
        return this.codDepar;
    }
    
    public void setCodDepar(String codDepar) {
        this.codDepar = codDepar;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DepartamentoId) ) return false;
		 DepartamentoId castOther = ( DepartamentoId ) other; 
         
		 return ( (this.getCodCia()==castOther.getCodCia()) || ( this.getCodCia()!=null && castOther.getCodCia()!=null && this.getCodCia().equals(castOther.getCodCia()) ) )
 && ( (this.getCodDepar()==castOther.getCodDepar()) || ( this.getCodDepar()!=null && castOther.getCodDepar()!=null && this.getCodDepar().equals(castOther.getCodDepar()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCodCia() == null ? 0 : this.getCodCia().hashCode() );
         result = 37 * result + ( getCodDepar() == null ? 0 : this.getCodDepar().hashCode() );
         return result;
   }   


}


