package com.domain.sysassets;
// Generated 01/08/2018 09:51:25 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Departamento generated by hbm2java
 */
public class Departamento  implements java.io.Serializable {


     private DepartamentoId id;
     private String descripcion;
     private Set<ActivosFijos> activosFijoses = new HashSet<ActivosFijos>(0);
     private Set<Encargado> encargados = new HashSet<Encargado>(0);

    public Departamento() {
    }

	
    public Departamento(DepartamentoId id) {
        this.id = id;
    }
    public Departamento(DepartamentoId id, String descripcion, Set<ActivosFijos> activosFijoses, Set<Encargado> encargados) {
       this.id = id;
       this.descripcion = descripcion;
       this.activosFijoses = activosFijoses;
       this.encargados = encargados;
    }
   
    public DepartamentoId getId() {
        return this.id;
    }
    
    public void setId(DepartamentoId id) {
        this.id = id;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<ActivosFijos> getActivosFijoses() {
        return this.activosFijoses;
    }
    
    public void setActivosFijoses(Set<ActivosFijos> activosFijoses) {
        this.activosFijoses = activosFijoses;
    }
    public Set<Encargado> getEncargados() {
        return this.encargados;
    }
    
    public void setEncargados(Set<Encargado> encargados) {
        this.encargados = encargados;
    }




}


