package com.domain.sysassets;
// Generated 01/08/2018 09:51:25 PM by Hibernate Tools 4.3.1



/**
 * DepreciacionId generated by hbm2java
 */
public class DepreciacionId  implements java.io.Serializable {


     private String codCia;
     private long codActivo;
     private int numDepreciacion;

    public DepreciacionId() {
    }

    public DepreciacionId(String codCia, long codActivo, int numDepreciacion) {
       this.codCia = codCia;
       this.codActivo = codActivo;
       this.numDepreciacion = numDepreciacion;
    }
   
    public String getCodCia() {
        return this.codCia;
    }
    
    public void setCodCia(String codCia) {
        this.codCia = codCia;
    }
    public long getCodActivo() {
        return this.codActivo;
    }
    
    public void setCodActivo(long codActivo) {
        this.codActivo = codActivo;
    }
    public int getNumDepreciacion() {
        return this.numDepreciacion;
    }
    
    public void setNumDepreciacion(int numDepreciacion) {
        this.numDepreciacion = numDepreciacion;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DepreciacionId) ) return false;
		 DepreciacionId castOther = ( DepreciacionId ) other; 
         
		 return ( (this.getCodCia()==castOther.getCodCia()) || ( this.getCodCia()!=null && castOther.getCodCia()!=null && this.getCodCia().equals(castOther.getCodCia()) ) )
 && (this.getCodActivo()==castOther.getCodActivo())
 && (this.getNumDepreciacion()==castOther.getNumDepreciacion());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCodCia() == null ? 0 : this.getCodCia().hashCode() );
         result = 37 * result + (int) this.getCodActivo();
         result = 37 * result + this.getNumDepreciacion();
         return result;
   }   


}


