package com.domain.sysassets;
// Generated 01/08/2018 09:51:25 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Depreciacion generated by hbm2java
 */
public class Depreciacion  implements java.io.Serializable {


     private DepreciacionId id;
     private ActivosFijos activosFijos;
     private Date fechaDepreciacion;
     private Short anoFiscal;
     private Byte perProceso;
     private String numDocto;
     private BigDecimal montoDepreciacion;
     private String observaciones;

    public Depreciacion() {
    }

	
    public Depreciacion(DepreciacionId id, ActivosFijos activosFijos, String numDocto) {
        this.id = id;
        this.activosFijos = activosFijos;
        this.numDocto = numDocto;
    }
    public Depreciacion(DepreciacionId id, ActivosFijos activosFijos, Date fechaDepreciacion, Short anoFiscal, Byte perProceso, String numDocto, BigDecimal montoDepreciacion, String observaciones) {
       this.id = id;
       this.activosFijos = activosFijos;
       this.fechaDepreciacion = fechaDepreciacion;
       this.anoFiscal = anoFiscal;
       this.perProceso = perProceso;
       this.numDocto = numDocto;
       this.montoDepreciacion = montoDepreciacion;
       this.observaciones = observaciones;
    }
   
    public DepreciacionId getId() {
        return this.id;
    }
    
    public void setId(DepreciacionId id) {
        this.id = id;
    }
    public ActivosFijos getActivosFijos() {
        return this.activosFijos;
    }
    
    public void setActivosFijos(ActivosFijos activosFijos) {
        this.activosFijos = activosFijos;
    }
    public Date getFechaDepreciacion() {
        return this.fechaDepreciacion;
    }
    
    public void setFechaDepreciacion(Date fechaDepreciacion) {
        this.fechaDepreciacion = fechaDepreciacion;
    }
    public Short getAnoFiscal() {
        return this.anoFiscal;
    }
    
    public void setAnoFiscal(Short anoFiscal) {
        this.anoFiscal = anoFiscal;
    }
    public Byte getPerProceso() {
        return this.perProceso;
    }
    
    public void setPerProceso(Byte perProceso) {
        this.perProceso = perProceso;
    }
    public String getNumDocto() {
        return this.numDocto;
    }
    
    public void setNumDocto(String numDocto) {
        this.numDocto = numDocto;
    }
    public BigDecimal getMontoDepreciacion() {
        return this.montoDepreciacion;
    }
    
    public void setMontoDepreciacion(BigDecimal montoDepreciacion) {
        this.montoDepreciacion = montoDepreciacion;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }




}


