package com.domain.sysassets;
// Generated 01/08/2018 09:51:25 PM by Hibernate Tools 4.3.1



/**
 * EncargadoId generated by hbm2java
 */
public class EncargadoId  implements java.io.Serializable {


     private String codCia;
     private String idEncargado;

    public EncargadoId() {
    }

    public EncargadoId(String codCia, String idEncargado) {
       this.codCia = codCia;
       this.idEncargado = idEncargado;
    }
   
    public String getCodCia() {
        return this.codCia;
    }
    
    public void setCodCia(String codCia) {
        this.codCia = codCia;
    }
    public String getIdEncargado() {
        return this.idEncargado;
    }
    
    public void setIdEncargado(String idEncargado) {
        this.idEncargado = idEncargado;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EncargadoId) ) return false;
		 EncargadoId castOther = ( EncargadoId ) other; 
         
		 return ( (this.getCodCia()==castOther.getCodCia()) || ( this.getCodCia()!=null && castOther.getCodCia()!=null && this.getCodCia().equals(castOther.getCodCia()) ) )
 && ( (this.getIdEncargado()==castOther.getIdEncargado()) || ( this.getIdEncargado()!=null && castOther.getIdEncargado()!=null && this.getIdEncargado().equals(castOther.getIdEncargado()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCodCia() == null ? 0 : this.getCodCia().hashCode() );
         result = 37 * result + ( getIdEncargado() == null ? 0 : this.getIdEncargado().hashCode() );
         return result;
   }   


}


