package com.domain.sysassets;
// Generated 01/08/2018 09:51:25 PM by Hibernate Tools 4.3.1



/**
 * EstadoActivo generated by hbm2java
 */
public class EstadoActivo  implements java.io.Serializable {


     private String estado;
     private String descripcion;

    public EstadoActivo() {
    }

	
    public EstadoActivo(String estado) {
        this.estado = estado;
    }
    public EstadoActivo(String estado, String descripcion) {
       this.estado = estado;
       this.descripcion = descripcion;
    }
   
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


