package com.domain.sysassets;
// Generated 01/08/2018 09:51:25 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Localizacion generated by hbm2java
 */
public class Localizacion  implements java.io.Serializable {


     private String codLocalizacion;
     private String descripcion;
     private Set<ActivosFijos> activosFijoses = new HashSet<ActivosFijos>(0);

    public Localizacion() {
    }

	
    public Localizacion(String codLocalizacion) {
        this.codLocalizacion = codLocalizacion;
    }
    public Localizacion(String codLocalizacion, String descripcion, Set<ActivosFijos> activosFijoses) {
       this.codLocalizacion = codLocalizacion;
       this.descripcion = descripcion;
       this.activosFijoses = activosFijoses;
    }
   
    public String getCodLocalizacion() {
        return this.codLocalizacion;
    }
    
    public void setCodLocalizacion(String codLocalizacion) {
        this.codLocalizacion = codLocalizacion;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<ActivosFijos> getActivosFijoses() {
        return this.activosFijoses;
    }
    
    public void setActivosFijoses(Set<ActivosFijos> activosFijoses) {
        this.activosFijoses = activosFijoses;
    }




}


