package com.domain.sysassets;
// Generated 01/08/2018 09:51:25 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Mejoras generated by hbm2java
 */
public class Mejoras  implements java.io.Serializable {


     private MejorasId id;
     private ActivosFijos activosFijos;
     private Date fechaMejora;
     private Short anoFiscal;
     private Byte perProceso;
     private String numDocto;
     private BigDecimal montoMejora;
     private String observaciones;

    public Mejoras() {
    }

	
    public Mejoras(MejorasId id, ActivosFijos activosFijos, String numDocto) {
        this.id = id;
        this.activosFijos = activosFijos;
        this.numDocto = numDocto;
    }
    public Mejoras(MejorasId id, ActivosFijos activosFijos, Date fechaMejora, Short anoFiscal, Byte perProceso, String numDocto, BigDecimal montoMejora, String observaciones) {
       this.id = id;
       this.activosFijos = activosFijos;
       this.fechaMejora = fechaMejora;
       this.anoFiscal = anoFiscal;
       this.perProceso = perProceso;
       this.numDocto = numDocto;
       this.montoMejora = montoMejora;
       this.observaciones = observaciones;
    }
   
    public MejorasId getId() {
        return this.id;
    }
    
    public void setId(MejorasId id) {
        this.id = id;
    }
    public ActivosFijos getActivosFijos() {
        return this.activosFijos;
    }
    
    public void setActivosFijos(ActivosFijos activosFijos) {
        this.activosFijos = activosFijos;
    }
    public Date getFechaMejora() {
        return this.fechaMejora;
    }
    
    public void setFechaMejora(Date fechaMejora) {
        this.fechaMejora = fechaMejora;
    }
    public Short getAnoFiscal() {
        return this.anoFiscal;
    }
    
    public void setAnoFiscal(Short anoFiscal) {
        this.anoFiscal = anoFiscal;
    }
    public Byte getPerProceso() {
        return this.perProceso;
    }
    
    public void setPerProceso(Byte perProceso) {
        this.perProceso = perProceso;
    }
    public String getNumDocto() {
        return this.numDocto;
    }
    
    public void setNumDocto(String numDocto) {
        this.numDocto = numDocto;
    }
    public BigDecimal getMontoMejora() {
        return this.montoMejora;
    }
    
    public void setMontoMejora(BigDecimal montoMejora) {
        this.montoMejora = montoMejora;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }




}


