package com.domain.sysassets;
// Generated 01/08/2018 09:51:25 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Retiro generated by hbm2java
 */
public class Retiro  implements java.io.Serializable {


     private RetiroId id;
     private ActivosFijos activosFijos;
     private Date fechaRetiro;
     private Short anoFiscal;
     private Byte perProceso;
     private String numDocto;
     private String observaciones;

    public Retiro() {
    }

	
    public Retiro(ActivosFijos activosFijos, String numDocto) {
        this.activosFijos = activosFijos;
        this.numDocto = numDocto;
    }
    public Retiro(ActivosFijos activosFijos, Date fechaRetiro, Short anoFiscal, Byte perProceso, String numDocto, String observaciones) {
       this.activosFijos = activosFijos;
       this.fechaRetiro = fechaRetiro;
       this.anoFiscal = anoFiscal;
       this.perProceso = perProceso;
       this.numDocto = numDocto;
       this.observaciones = observaciones;
    }
   
    public RetiroId getId() {
        return this.id;
    }
    
    public void setId(RetiroId id) {
        this.id = id;
    }
    public ActivosFijos getActivosFijos() {
        return this.activosFijos;
    }
    
    public void setActivosFijos(ActivosFijos activosFijos) {
        this.activosFijos = activosFijos;
    }
    public Date getFechaRetiro() {
        return this.fechaRetiro;
    }
    
    public void setFechaRetiro(Date fechaRetiro) {
        this.fechaRetiro = fechaRetiro;
    }
    public Short getAnoFiscal() {
        return this.anoFiscal;
    }
    
    public void setAnoFiscal(Short anoFiscal) {
        this.anoFiscal = anoFiscal;
    }
    public Byte getPerProceso() {
        return this.perProceso;
    }
    
    public void setPerProceso(Byte perProceso) {
        this.perProceso = perProceso;
    }
    public String getNumDocto() {
        return this.numDocto;
    }
    
    public void setNumDocto(String numDocto) {
        this.numDocto = numDocto;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }




}


