package com.domain.sysassets;
// Generated 01/08/2018 09:51:25 PM by Hibernate Tools 4.3.1



/**
 * TipoActivo generated by hbm2java
 */
public class TipoActivo  implements java.io.Serializable {


     private TipoActivoId id;
     private CategoriaActivo categoriaActivo;
     private String descripcion;
     private String codigoPresup;
     private Short vidaUtil;

    public TipoActivo() {
    }

	
    public TipoActivo(TipoActivoId id, CategoriaActivo categoriaActivo) {
        this.id = id;
        this.categoriaActivo = categoriaActivo;
    }
    public TipoActivo(TipoActivoId id, CategoriaActivo categoriaActivo, String descripcion, String codigoPresup, Short vidaUtil) {
       this.id = id;
       this.categoriaActivo = categoriaActivo;
       this.descripcion = descripcion;
       this.codigoPresup = codigoPresup;
       this.vidaUtil = vidaUtil;
    }
   
    public TipoActivoId getId() {
        return this.id;
    }
    
    public void setId(TipoActivoId id) {
        this.id = id;
    }
    public CategoriaActivo getCategoriaActivo() {
        return this.categoriaActivo;
    }
    
    public void setCategoriaActivo(CategoriaActivo categoriaActivo) {
        this.categoriaActivo = categoriaActivo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getCodigoPresup() {
        return this.codigoPresup;
    }
    
    public void setCodigoPresup(String codigoPresup) {
        this.codigoPresup = codigoPresup;
    }
    public Short getVidaUtil() {
        return this.vidaUtil;
    }
    
    public void setVidaUtil(Short vidaUtil) {
        this.vidaUtil = vidaUtil;
    }




}


