package com.domain.sysassets;
// Generated 01/08/2018 09:51:25 PM by Hibernate Tools 4.3.1



/**
 * TipoActivoId generated by hbm2java
 */
public class TipoActivoId  implements java.io.Serializable {


     private String categoria;
     private String tipActivo;

    public TipoActivoId() {
    }

    public TipoActivoId(String categoria, String tipActivo) {
       this.categoria = categoria;
       this.tipActivo = tipActivo;
    }
   
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }
    public String getTipActivo() {
        return this.tipActivo;
    }
    
    public void setTipActivo(String tipActivo) {
        this.tipActivo = tipActivo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TipoActivoId) ) return false;
		 TipoActivoId castOther = ( TipoActivoId ) other; 
         
		 return ( (this.getCategoria()==castOther.getCategoria()) || ( this.getCategoria()!=null && castOther.getCategoria()!=null && this.getCategoria().equals(castOther.getCategoria()) ) )
 && ( (this.getTipActivo()==castOther.getTipActivo()) || ( this.getTipActivo()!=null && castOther.getTipActivo()!=null && this.getTipActivo().equals(castOther.getTipActivo()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCategoria() == null ? 0 : this.getCategoria().hashCode() );
         result = 37 * result + ( getTipActivo() == null ? 0 : this.getTipActivo().hashCode() );
         return result;
   }   


}


