package com.domain.sysassets;
// Generated 01/08/2018 09:51:25 PM by Hibernate Tools 4.3.1



/**
 * TrasladosId generated by hbm2java
 */
public class TrasladosId  implements java.io.Serializable {


     private String codCia;
     private long codActivo;
     private int numTraslado;

    public TrasladosId() {
    }

    public TrasladosId(String codCia, long codActivo, int numTraslado) {
       this.codCia = codCia;
       this.codActivo = codActivo;
       this.numTraslado = numTraslado;
    }
   
    public String getCodCia() {
        return this.codCia;
    }
    
    public void setCodCia(String codCia) {
        this.codCia = codCia;
    }
    public long getCodActivo() {
        return this.codActivo;
    }
    
    public void setCodActivo(long codActivo) {
        this.codActivo = codActivo;
    }
    public int getNumTraslado() {
        return this.numTraslado;
    }
    
    public void setNumTraslado(int numTraslado) {
        this.numTraslado = numTraslado;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TrasladosId) ) return false;
		 TrasladosId castOther = ( TrasladosId ) other; 
         
		 return ( (this.getCodCia()==castOther.getCodCia()) || ( this.getCodCia()!=null && castOther.getCodCia()!=null && this.getCodCia().equals(castOther.getCodCia()) ) )
 && (this.getCodActivo()==castOther.getCodActivo())
 && (this.getNumTraslado()==castOther.getNumTraslado());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCodCia() == null ? 0 : this.getCodCia().hashCode() );
         result = 37 * result + (int) this.getCodActivo();
         result = 37 * result + this.getNumTraslado();
         return result;
   }   


}


